[project]
name = "imgs2pdf"
version = "3.1.1"
description = "Imgs2PDF is a tool that makes PDF files from collections of independent image files."
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["pillow", "reportlab"]

[tool.jedi-language-server]
line-length = 79
